### ISSUE TITLE
Implement GraphQL -- or don't

### ISSUE THREAD

**Issue by golemheavy** [the-warp-zone/WorkOrderWizard#3]
We ended up not adding GraphQL

**Comment by toobaditstaken** [comment]
i will be investigation into GraphQl to see if its worthwhile to use it, anything worth reviewing i will be putting links into comments here.

**Comment by golemheavy** [comment]
https://www.youtube.com/watch?v=NeQfq0U5LnI

**Comment by golemheavy** [comment]
GraphQL Schema (Stubbed):

type User {
	name: String!
	email: String!
	company_name: String!    // users's company's name
	customers: [Customer!]!
	paymentmethods: [PaymentMethod!]!
}

type Customer {
	name: String!
	phone: String!
	owner: User!
	business_name: String!
	workorders: [WorkOrder!]!
}

type WorkOrder {
	customer: Customer!
	invoices: [Invoice!]!
	costs: [Cost!]!
}

type Invoice {
	workorder: WorkOrder!
}

type Cost {
	workorder: WorkOrder!
}

type PaymentMethod {
	user: User!
	cc_hash: Int!
	exp_date: Date!
	cvv_code: Int!
}

**Comment by golemheavy** [comment]
So at this time if I am not mistaken we aren't planning on using GraphQL, but there is a possibility of implementing it later. However, we are moving forward with Redux regardless.
